# Generated by Django 3.2.18 on 2023-03-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('complement_adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('prix_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='QuittanceLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_locataire.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_locataire.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarques', models.TextField()),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_locataire.appartement')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_locataire.locataire'),
        ),
    ]
