# Generated by Django 3.2.18 on 2023-03-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_locataire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='affecter_appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
