# Generated by Django 3.2.18 on 2023-03-28 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_locataire', '0002_affecter_appartement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_locataire.appartement')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_locataire.locataire')),
            ],
        ),
        migrations.DeleteModel(
            name='affecter_appartement',
        ),
    ]
